### ISSUE TITLE
Error Handling when job state is "cancelled"

### ISSUE THREAD

**Issue by harkamvysis** [sassoftware/sas-airflow-provider#5]
Hi All, We have stumbled across some SAS studio flows that have a built in logic to abort. However that means that the job_state is set to "canceled" rather than "failed". Perhaps we should add error handling that takes this job state into account. Right now if a flow ends with a cancelled state airflow will mark it as successful in the web interface.

A potential fix would be to add a new airflow exception when job_state == "canceled" (note that "cancelled" with double "l" wont be accepted as a valid job state"

![image](https://user-images.githubusercontent.com/80230965/219656760-ec6f0b18-5b43-4b0d-b9b6-b6b1abf91000.png)

**Comment by Carus11** [comment]
What does the API return to denote cancelled vs the failed status? Is it surfaced as a regular json property, or a sysrc value?
